app/users/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for
from forms import LoginForm, PasswordForm, ProfileForm

bp = Blueprint('user', __name__, template_folder='templates')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        if form.email.data == "ticket@sample.com" and form.password.data == "user@123":
            flash(f'Welcome to HPI Ticketing System!', 'success')
            return redirect(url_for('user.home'))
        else:
            flash(f'Error login. Please check email and password.', 'danger')

    return render_template('user-login.html', form=form)

@bp.route('/profile', methods=['GET', 'POST'])
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        flash(f'Hi {form.firstname.data}, your information was updated successfully.', 'success')

    return render_template('user-profile.html', form=form)

@bp.route('/change-password', methods=['GET', 'POST'])
def change_pass():
    form = PasswordForm()
    if form.validate_on_submit():
        flash(f'Your password was updated successfully.', 'success')
        return redirect(url_for('user.home'))
    
    return render_template('user-change-pass.html', form=form)

@bp.route('/forgot-password')
def forgot_pass():  
    return render_template('user-forgot-password.html')

@bp.route('/home', methods=['GET', 'POST'])
def home():
    return render_template('user-home.html')

app/users/templates/user-base.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>HPI | Ticketing System</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Toastr -->
  <link rel="stylesheet" href="{{ url_for('static', filename='toastr/toastr.min.css') }}">
  <style>
    *:focus {
      outline: 0;
    }
    select{
      border: 0;
    }
    button:focus{
      outline: 0;
    }
    .table td, .table th{
      padding: 5px;
    }
    .timeline::before{
      top: 30px !important;
    }
  </style>
</head>
<body class="hold-transition layout-top-nav text-sm">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="{{ url_for('user.home') }}" class="navbar-brand">
        <span class="brand-text font-weight-light"><strong>HPI Ticketing</strong></span>
      </a>
      
      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Right navbar links -->
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="fas fa-cogs"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
            <a href="{{ url_for('user.profile') }}" class="dropdown-item">
              <i class="fas fa-id-card mr-2"></i>My Profile
            </a>
            <a href="{{ url_for('user.change_pass') }}" class="dropdown-item">
              <i class="fas fa-key mr-2"></i>Change Password
            </a>
          </div>
        </li>
        <li>
          <a class="nav-link" href="{{ url_for('user.login') }}">
            <i class="fas fa-sign-out-alt mr-2"></i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->
  {% block content %}
  {% endblock %}

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Version 1.0
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020 <a href="http://himlayangpilipino.com.ph/">Himlayang Pilipino, Inc.</a></strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ url_for('static', filename='jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='js/adminlte.min.js') }}"></script>
<!-- Toastr -->
<script src="{{ url_for('static', filename='toastr/toastr.min.js') }}"></script>
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <script>
        $('.toastrModal').click(function(){
          toastr.success('{{ message }}');
        })
        $('.toastrModal').click();
      </script>
    {% endfor %}
  {% endif %}
{% endwith %}
</body>
</html>

app/users/templates/user-change-pass.html
{% extends 'user-base.html' %}
{% block content %}
<div class="content-wrapper">
  <div class="content-header">
    <div class="container">
      <div class="row mb-2">
        <div class="col-sm-6 col-md-6 col-lg-6">
          <h1 class="m-0 text-dark">My<small> Password</small></h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div><!-- /.content-header -->
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-3 col-lg-3"></div>
        <div class="col-md-6 col-sm-6 col-lg-6">
          <div class="card card-primary card-outline">
            <div class="card-body register-card-body">
              <form action="" method="POST">
                {{ form.hidden_tag() }}
                <div class="modal-body">
                  <div class="form-group">
                    <label>{{ form.password.label() }}</label>
                    {% if form.password.errors %}
                      {{ form.password(class="form-control form-control-sm is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.password(class="form-control form-control-sm") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    <label>{{ form.confirm_password.label() }}</label>
                    {% if form.confirm_password.errors %}
                      {{ form.confirm_password(class="form-control form-control-sm is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.confirm_password(class="form-control form-control-sm") }}
                    {% endif %}
                  </div>
                </div>
                <div class="modal-footer justify-content-between">
                  {{ form.change(class="btn btn-primary") }}
                </div>
              </form>
            </div><!-- /.form-box -->
          </div> <!-- card -->
        </div> <!-- col-md-6 -->
      </div> <!-- row -->
    </div> <!-- container -->
  </div> <!-- content -->
</div>
<!-- /.login-box -->
{% endblock %}

app/users/templates/user-forgot-password.html
{% extends "index.html" %}
{% block content %}
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>

      <form action="" method="post">
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="/user/login">Back to Login Page</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

app/users/templates/user-home.html
{% extends 'user-base.html' %}
  {% block content %}
    <!-- Content Header (Page header) -->
  <div class="content-wrapper">
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6 col-md-6 col-lg-6">
            <h1 class="m-0 text-dark">My<small> Tickets</small></h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-sm-12 col-md-12">
            <div class="card card-primary card-outline">
                <div class="card-header">
                  <h3 class="card-title dropdown">
                    <div>
                      <select>
                        <option selected>Open</option>
                        <option>Unassigned</option>
                        <option>Closed</option>
                      </select>
                    </div>
                  </h3>
  
                  <div class="card-tools">
                    <div class="input-group input-group-sm">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
  
                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </div>
                  <div class="card-tools">
                    <div class="input-group input-group-sm">
                      <div class="input-group-append">
                        <button type="button" class="btn btn-default">
                          <i class="fas fa-sync"></i>
                        </button>&nbsp;
                        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#AddTicketModal">
                          <i class="fas fa-plus"></i>&nbsp;Add Ticket
                        </button>
                      </div>
                      &nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0" style="height: 300px;">
                  <table class="table table-head-fixed text-nowrap">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>User</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Reason</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>183</td>
                        <td>John Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-success">Approved</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>219</td>
                        <td>Alexander Pierce</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-warning">Pending</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>657</td>
                        <td>Bob Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-primary">Approved</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>175</td>
                        <td>Mike Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-danger">Denied</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>134</td>
                        <td>Jim Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-success">Approved</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>494</td>
                        <td>Victoria Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-warning">Pending</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>832</td>
                        <td>Michael Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-primary">Approved</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                      <tr>
                        <td>982</td>
                        <td>Rocky Doe</td>
                        <td>11-7-2014</td>
                        <td><span class="tag tag-danger">Denied</span></td>
                        <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
            </div><!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
          <div class="col-lg-12 col-sm-12 col-md-12">
            <div class="timeline card card-primary card-outline">
              <br>
              <!-- timeline item -->
              <div>
                <i class="fas fa-envelope bg-blue"></i>
                <div class="timeline-item">
                  <span class="time"><i class="fas fa-clock"></i> 12:05</span>
                  <h3 class="timeline-header"><a href="#">Support Team</a> sent you an email</h3>

                  <div class="timeline-body">
                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                    weebly ning heekya handango imeem plugg dopplr jibjab, movity
                    jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle
                    quora plaxo ideeli hulu weebly balihoo...
                  </div>
                  <div class="timeline-footer">
                    <a class="btn btn-primary btn-sm">Read more</a>
                    <a class="btn btn-danger btn-sm toastrModal">Delete</a>
                  </div>
                </div>
              </div>
              <!-- END timeline item -->
              <!-- timeline item -->
              <div>
                <i class="fas fa-comment-dots"></i>
                <div class="timeline-item">
                  <span class="time"><i class="fas fa-clock"></i> 5 mins ago</span>
                  <h3 class="timeline-header no-border"><a href="#">Sarah Young</a> accepted your friend request</h3>
                </div>
              </div>
              <!-- END timeline item -->
              <div>
                <i class="fas fa-envelope bg-blue"></i>
              </div>
            </div>
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
    <div class="modal fade" id="AddTicketModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">New Ticket</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <label for="subject">Subject</label>
              <input type="text" class="form-control form-control-sm" id="subject" placeholder="Subject">
            </div>
            <div class="form-group">
              <label for="description">Description</label>
              <textarea class="form-control form-control-sm" id="description" placeholder=""></textarea>
            </div>
            <div class="form-group">
              <label for="assignee">Assignee</label>
              <select class="form-control form-control-sm" name="assignee" id="assignee">
                <option value="" selected disabled>Assign your ticket..</option>
              </select>
            </div>
            <div class="form-group">
              <label for="category">Category</label>
              <select class="form-control form-control-sm" name="category" id="category">
                <option value="" selected disabled>Select a category..</option>
                <option value="Email">Email</option>
                <option value="Hardware">Hardware</option>
                <option value="Software">Software</option>
                <option value="Maintenance">Maintenance</option>
                <option value="Printer">Printer</option>
                <option value="Network">Network</option>
              </select>
            </div>
          </div>
          <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save</button>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
  </div>
  {% endblock %}

  

app/users/templates/user-index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>HPI | Ticket System</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ url_for('static', filename='icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Toastr -->
  <link rel="stylesheet" href="{{ url_for('static', filename='toastr/toastr.min.css') }}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  {% with err_messages = get_flashed_messages(with_categories=true) %}
  {% if err_messages %}
    {% for category, message in err_messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
  <div class="login-logo">
    <a href="/login"><b>HPI</b> Ticketing System</a>
  </div>
  {% block content %}
  {% endblock %}
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ url_for('static', filename='jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='js/adminlte.min.js') }}"></script>
<!-- Toastr -->
<script src="{{ url_for('static', filename='toastr/toastr.min.js') }}"></script>
</body>
</html>

app/users/templates/user-login.html
{% extends "user-index.html" %}
{% block content %}
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-group mb-3">
          {% if form.email.errors %}
            {{ form.email(class="form-control is-invalid") }}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
          {{ form.email(class="form-control", placeholder="Email") }}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
          {% endif %}
        </div>
        <div class="input-group mb-3">
          {{ form.password(class="form-control", placeholder="Password") }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              {{ form.remember() }}
              <label for="remember">
                {{ form.remember.label()}}
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            {{ form.submit(class="btn btn-primary btn-block") }}
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mb-1">
        <a href="{{ url_for('user.forgot_pass') }}">I forgot my password</a>
      </p>
      <!-- <p class="mb-0">
        <a href="register.html" class="text-center">Register a new membership</a>
      </p> -->
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
{% endblock %}

app/users/templates/user-profile.html
{% extends 'user-base.html' %}
{% block content %}
<div class="content-wrapper">
  <div class="content-header">
    <div class="container">
      <div class="row mb-2">
        <div class="col-sm-6 col-md-6 col-lg-6">
          <h1 class="m-0 text-dark">My<small> Profile</small></h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div><!-- /.content-header -->
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-3 col-lg-3"></div>
        <div class="col-md-6 col-sm-6 col-lg-6">
          <div class="card card-primary card-outline">
            <div class="card-body register-card-body">
              <form action="" method="POST">
                {{ form.hidden_tag() }}
                <div class="modal-body">
                  <div class="form-group">
                    <label>{{ form.firstname.label() }}</label>
                    {% if form.firstname.errors %}
                      {{ form.firstname(class="form-control form-control-sm is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.firstname.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.firstname(class="form-control form-control-sm") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    <label>{{ form.lastname.label() }}</label>
                    {% if form.lastname.errors %}
                      {{ form.lastname(class="form-control form-control-sm is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.lastname.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.lastname(class="form-control form-control-sm") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    <label>{{ form.middle_initial.label() }}</label>
                    {% if form.middle_initial.errors %}
                      {{ form.middle_initial(class="form-control form-control-sm is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.middle_initial.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.middle_initial(class="form-control form-control-sm") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    <label for="Department">Department</label>
                    <select name="department" id="Department" class="form-control form-control-sm">
                      <option value="" selected disabled>Select a department</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="Position">Position</label>
                    <select name="position" id="Position" class="form-control form-control-sm">
                      <option value="" selected disabled>Select a position</option>
                    </select>
                  </div>
                </div>
                <div class="modal-footer justify-content-between">
                  {{ form.save(class="btn btn-primary") }}
                </div>
              </form>
            </div><!-- /.form-box -->
          </div> <!-- card -->
        </div> <!-- col-md-6 -->
      </div> <!-- row -->
    </div> <!-- container -->
  </div> <!-- content -->
</div>
<!-- content-wrapper -->
<!-- /.register-box -->
{% endblock %}